version: '3.9'

networks:
  database:
    name: database
    driver: bridge
  gateway:
    name: database
    external: true

services:
  gateway:
    image: 'ghcr.io/undercurrent-technologies/gateway:dev'
    container_name: 'gateway'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ACCESS_USER=${ACCESS_USER}
        - ACCESS_TOKEN=${ACCESS_TOKEN}
        - UTILITIES=${UTILITIES}
    networks:
      - database
      - gateway
    env_file:
      - .env
    ports:
      - 8080:8080
