apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: gateway
        image: ghcr.io/undercurrent-technologies/gateway:dev
        env: 
          - name: APP_VERSION
            value: "1.0.0"
          - name: APP_ENV
            value: development
          - name: PORT
            value: "8082"
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: kprime-secret
                key: JWT_KEY
          - name: MONGO_DB
            value: option_exchange
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: kprime-secret
                key: MONGO_URL
          - name: KAFKA_BROKER
            valueFrom:
              secretKeyRef:
                name: kprime-secret
                key: BROKER_URL
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: kprime-secret
                key: REDIS_URL
          - name: JWT_REMEMBER_TOKEN_EXPIRE
            value: "31536000"
          - name: JWT_REMEMBER_REFRESH_TOKEN_EXPIRE
            value: "41536000"
          - name: RATE_LIMITER_MAX_REQUESTS
            value: "1000"
          - name: RATE_LIMITER_DURATION
            value: "1"
          - name: PROTECT_BASIC_ENGINE
            valueFrom:
              secretKeyRef:
                key: PROTECT_BASIC
          - name: LOG_WITH_PAPERTRAIL
            value: "false"
          - name: MATCHING_ENGINE_URL
            value: matching-engine-service:8080
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
