// Code generated by MockGen. DO NOT EDIT.
// Source: gateway/internal/auth/controller (interfaces: IAuthHandler)

// Package mock_controller is a generated GoMock package.
package mock_controller

import (
        reflect "reflect"

        gin "github.com/gin-gonic/gin"
        gomock "github.com/golang/mock/gomock"
)

// MockIAuthHandler is a mock of IAuthHandler interface.
type MockIAuthHandler struct {
        ctrl     *gomock.Controller
        recorder *MockIAuthHandlerMockRecorder
}

// MockIAuthHandlerMockRecorder is the mock recorder for MockIAuthHandler.
type MockIAuthHandlerMockRecorder struct {
        mock *MockIAuthHandler
}

// NewMockIAuthHandler creates a new mock instance.
func NewMockIAuthHandler(ctrl *gomock.Controller) *MockIAuthHandler {
        mock := &MockIAuthHandler{ctrl: ctrl}
        mock.recorder = &MockIAuthHandlerMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthHandler) EXPECT() *MockIAuthHandlerMockRecorder {
        return m.recorder
}

// AdminLogin mocks base method.
func (m *MockIAuthHandler) AdminLogin(arg0 *gin.Context) {
        m.ctrl.T.Helper()
        m.ctrl.Call(m, "AdminLogin", arg0)
}

// AdminLogin indicates an expected call of AdminLogin.
func (mr *MockIAuthHandlerMockRecorder) AdminLogin(arg0 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminLogin", reflect.TypeOf((*MockIAuthHandler)(nil).AdminLogin), arg0)
}

// Login mocks base method.
func (m *MockIAuthHandler) Login(arg0 *gin.Context) {
        m.ctrl.T.Helper()
        m.ctrl.Call(m, "Login", arg0)
}

// Login indicates an expected call of Login.
func (mr *MockIAuthHandlerMockRecorder) Login(arg0 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockIAuthHandler)(nil).Login), arg0)
}