// Code generated by MockGen. DO NOT EDIT.
// Source: gateway/internal/auth/service (interfaces: IAuthService)

// Package mock_service is a generated GoMock package.
package mock_service

import (
        context "context"
        model "gateway/internal/auth/model"
        reflect "reflect"

        gomock "github.com/golang/mock/gomock"
)

// MockIAuthService is a mock of IAuthService interface.
type MockIAuthService struct {
        ctrl     *gomock.Controller
        recorder *MockIAuthServiceMockRecorder
}

// MockIAuthServiceMockRecorder is the mock recorder for MockIAuthService.
type MockIAuthServiceMockRecorder struct {
        mock *MockIAuthService
}

// NewMockIAuthService creates a new mock instance.
func NewMockIAuthService(ctrl *gomock.Controller) *MockIAuthService {
        mock := &MockIAuthService{ctrl: ctrl}
        mock.recorder = &MockIAuthServiceMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthService) EXPECT() *MockIAuthServiceMockRecorder {
        return m.recorder
}

// AdminLogin mocks base method.
func (m *MockIAuthService) AdminLogin(arg0 context.Context, arg1 model.LoginRequest) (string, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "AdminLogin", arg0, arg1)
        ret0, _ := ret[0].(string)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// AdminLogin indicates an expected call of AdminLogin.
func (mr *MockIAuthServiceMockRecorder) AdminLogin(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminLogin", reflect.TypeOf((*MockIAuthService)(nil).AdminLogin), arg0, arg1)
}

// Login mocks base method.
func (m *MockIAuthService) Login(arg0 context.Context, arg1 model.LoginRequest) (string, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Login", arg0, arg1)
        ret0, _ := ret[0].(string)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockIAuthServiceMockRecorder) Login(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockIAuthService)(nil).Login), arg0, arg1)
}

// Logout mocks base method.
func (m *MockIAuthService) Logout(arg0 context.Context) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Logout", arg0)
        ret0, _ := ret[0].(error)
        return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockIAuthServiceMockRecorder) Logout(arg0 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockIAuthService)(nil).Logout), arg0)
}